menus/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView

from .views import (
    ItemCreateView,
    ItemDetailView,
    ItemListView,
    ItemUpdateView
    )

urlpatterns = [
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    #url(r'^(?P<pk>[\w-]+)/edit/$', ItemUpdateView.as_view(), name='edit'),
    url(r'^(?P<pk>[\w-]+)/$', ItemUpdateView.as_view(), name='detail'),
    url(r'$', ItemListView.as_view(), name='list'),
    ]

muypick/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView

from restaurants.views import (
    RestaurantListView,
    RestaurantDetailView,
    RestaurantCreateView
    )

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
]

restaurants/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView

from .views import (
    RestaurantListView,
    RestaurantDetailView,
    RestaurantCreateView,
    RestaurantUpdateView
    )

urlpatterns = [
    url(r'^create/$', RestaurantCreateView.as_view(), name='create'),
    #url(r'^(?P<slug>[\w-]+)/edit/$', RestaurantUpdateView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/$', RestaurantUpdateView.as_view(), name='detail'),
    url(r'$', RestaurantListView.as_view(), name='list'),
    ]

restaurants/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.core.urlresolvers import reverse
from .utils import unique_slug_generator
from .validators import validate_category

User = settings.AUTH_USER_MODEL

# Create your models here.
class RestaurantLocation(models.Model):

    owner       = models.ForeignKey(User)
    name        = models.CharField(max_length=120)
    location    = models.CharField(max_length=120, blank=True, null=True)
    category    = models.CharField(max_length=120, blank=True, null=True, validators=[validate_category])
    timestamp   = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)
    slug        = models.SlugField(unique=True, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('restaurants:detail', kwargs={'slug': self.slug})

    @property
    def title(self):
        return self.name

def rl_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(rl_pre_save_receiver, sender=RestaurantLocation)

restaurants/forms.py
from django import forms

from .models import RestaurantLocation

class RestaurantCreateForm(forms.Form):
    name            = forms.CharField()
    location        = forms.CharField(required=False)
    category        = forms.CharField(required=False)

    def clean_name(self):
        name = self.cleaned_data.get("name")
        if name == "Hello":
            raise forms.ValidationError("Not a valid name")
        return name

class RestaurantLocationCreateForm(forms.ModelForm):
    class Meta:
        model = RestaurantLocation
        fields = [
            'name',
            'location',
            'category',
            'slug',
        ]

    def clean_name(self):
        name = self.cleaned_data.get("name")
        if name == "Hello":
            raise forms.ValidationError("Not a valid name")
        return name

restaurants/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from .forms import RestaurantLocationCreateForm
from .models import RestaurantLocation

class RestaurantListView(LoginRequiredMixin, ListView):
    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)

class RestaurantDetailView(LoginRequiredMixin, DetailView):
    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)

class RestaurantCreateView(LoginRequiredMixin, CreateView):
    form_class = RestaurantLocationCreateForm
    template_name = 'restaurants/restaurant_create_form.html'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner = self.request.user
        return super(RestaurantCreateView, self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super(RestaurantCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Add Restaurant'
        return context

class RestaurantUpdateView(LoginRequiredMixin, UpdateView):
    form_class = RestaurantLocationCreateForm
    template_name = 'restaurants/detail-update.html'

    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner = self.request.user
        return super(RestaurantUpdateView, self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super(RestaurantUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Update Restaurant: ' + self.get_object().name
        return context

restaurants/templates/restaurants/detail-update.html
{% extends "base.html" %}

{% block head_title %}
  {{ form.instance.title}} || {{ block.super }}
{% endblock %}


{% block content %}
<h1>{{ form.instance.name }} <small> {{ form.instance.category }}</small></h1>
<p>{{ form.instance.location }}</p>
<p>{{ form.instance.owner }}</p>
<p>Created: {{ form.instance.timestamp }}</p>
<p>Updated {{ form.instance.updated|timesince }} ago</p>

<hr>
<h3>Make Changes</h3>
{% include "snippets/form-snippet.html" with form=form %}

{% endblock content %}

restaurants/templates/restaurants/restaurant_create_form.html
{% extends "base.html" %}

{% block head_title %}Create a Restaurant || {{block.super}} {% endblock head_title %}

{% block content %}
<h1>Create a Restaurant</h1>


<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>
{% endblock content %}

restaurants/templates/restaurants/restaurant_detail.html
{% extends "base.html" %}

{% block content %}
<h1>{{ object.name }} <small> {{ object.category }}</small></h1>
<p>{{ object.location }}</p>
<p>Created: {{ object.timestamp }}</p>
<p>Updated {{ object.updated|timesince }} ago</p>
{% endblock content %}

restaurants/templates/restaurants/restaurantlocation_detail.html
{% extends "base.html" %}

{% block content %}
<h1>{{ object.name }} <small> {{ object.category }}</small></h1>
<p>{{ object.location }}</p>
<p>{{ object.owner }}</p>
<p>Created: {{ object.timestamp }}</p>
<p>Updated {{ object.updated|timesince }} ago</p>
{% endblock content %}

restaurants/templates/restaurants/restaurantlocation_list.html
{% extends "base.html" %}

  {% block head_title %}My Restaurants || {{block.super}} {% endblock head_title %}

{% block content %}
<h1>My Restaurants <small><a href="{% url 'restaurants:create' %}">Add</a></small></h1>

<ul>
  {% for obj in object_list %}
    <li><a href="{{ obj.get_absolute_url }}">{{ obj.name }}</a><br>
      {{ obj.location }} {{ obj.owner }} {{ obj.category }} {{ obj.timestamp }}</li>
  {% empty %}
    <li><a href="{% url 'restaurants:create' %}">Add a Restauran</a></li>
  {% endfor %}
</ul>
{% endblock content %}}

restaurants/templates/restaurants/restaurants_list.html
{% extends "base.html" %}

  {% block head_title %}My Restaurants || {{block.super}} {% endblock head_title %}

{% block content %}
<h1>Restaurant List</h1>

<ul>
  {% for obj in object_list %}
    <li><a href="/restaurants/{{obj.slug}}">{{ obj.name }}</a><br>
      {{ obj.location }} {{ obj.category }} {{ obj.timestamp }}</li>
  {% endfor %}
</ul>
{% endblock content %}}