menus/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView

from .views import (
    ItemCreateView,
    ItemDetailView,
    ItemListView,
    ItemUpdateView
    )

urlpatterns = [
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    #url(r'^(?P<pk>[\w-]+)/edit/$', ItemUpdateView.as_view(), name='edit'),
    url(r'^(?P<pk>[\w-]+)/$', ItemUpdateView.as_view(), name='detail'),
    url(r'$', ItemListView.as_view(), name='list'),
    ]

muypick/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView

from restaurants.views import (
    RestaurantListView,
    RestaurantDetailView,
    RestaurantCreateView
    )

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
]

templates/snippets/css.html
<!-- Bootstrap -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

templates/snippets/form-snippet.html
{% if form.errors.non_field_errors %}
  {{ form.errors.non_field_errors }}
{% endif %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>

templates/snippets/js.html
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

templates/snippets/nav.html
  <h1>MuyPicky.com</h1>
  <a href="{% url 'home' %}">Home</a>
  {% if request.user.is_authenticated %}
    <a href="{% url 'restaurants:list' %}">Restaurants</a>
    <a href="{% url 'menus:list' %}">Items</a>
  {% endif %}
  <a href="{% url 'about' %}">About</a>
  <a href="{% url 'contact' %}">Contact</a>

templates/snippets/restaurant_create_form.html
{% extends "base.html" %}

{% block head_title %}{{ title }} || {{block.super}} {% endblock head_title %}

{% block content %}
<h1>{{ title }}</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>
{% endblock content %}

templates/snippets/sidebar.html
<ul>
  <li>Item 1</li>
  <li>Item 2</li>
  <li>Item 3</li>
</ul>