menus/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView

from .views import (
    ItemCreateView,
    ItemDetailView,
    ItemListView,
    ItemUpdateView
    )

urlpatterns = [
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    #url(r'^(?P<pk>[\w-]+)/edit/$', ItemUpdateView.as_view(), name='edit'),
    url(r'^(?P<pk>[\w-]+)/$', ItemUpdateView.as_view(), name='detail'),
    url(r'$', ItemListView.as_view(), name='list'),
    ]

muypick/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView

from restaurants.views import (
    RestaurantListView,
    RestaurantDetailView,
    RestaurantCreateView
    )

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
]

menus/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from restaurants.models import RestaurantLocation

class Item(models.Model):
    user        = models.ForeignKey(settings.AUTH_USER_MODEL)
    restaurant  = models.ForeignKey(RestaurantLocation)
    name        = models.CharField(max_length=120)
    contents    = models.TextField(help_text='separate each item by comma')
    excludes    = models.TextField(blank=True, null=True, help_text='separate each item by comma')
    public      = models.BooleanField(default=True)
    timestamp   = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name;

    def get_absolute_url(self):
        return reverse('menus:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-updated', '-timestamp']

    def get_contents(self):
        return self.contents.split(",")

    def get_excludes(self):
        return self.excludes.split(",")

menus/forms.py
from django import forms
from restaurants.models import RestaurantLocation
from .models import Item


class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = [
            'restaurant',
            'name',
            'contents',
            'excludes',
            'public'
        ]
    def __init__(self, user=None, *args, **kwargs):
        #print(user)
        super(ItemForm, self).__init__(*args, **kwargs)
        #self.fields['restaurant'].queryset = RestaurantLocation.objects.none()
        self.fields['restaurant'].queryset = RestaurantLocation.objects.filter(owner=user)#.exclude(item__isnull=False)

menus/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from .forms import ItemForm
from .models import Item


class ItemListView(ListView):

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

class ItemDetailView(DetailView):

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

class ItemCreateView(LoginRequiredMixin, CreateView):
    template_name = 'form.html'
    form_class = ItemForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        return super(ItemCreateView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(ItemCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(ItemCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Add Item'
        return context

class ItemUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'menus/detail-update.html'
    form_class = ItemForm

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(ItemUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Update Item'
        return context

    def get_form_kwargs(self):
        kwargs = super(ItemUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

menus/templates/menus/detail-update.html
{% extends "base.html" %}

  {% block head_title %}Menu Itens || {{block.super}} {% endblock head_title %}

{% block content %}
<h1>{{ form.instance.name }}</h1>
<h2>{{ form.instance.restaurant.name }}<small> {{form.instance.restaurant.location}}</small></h2>
{% if form.instance.contents %}
  <b>Contents</b>
  <ul>
    {% for item in form.instance.get_contents %}
      <li>{{ item }}</li>
    {% endfor %}
  </ul>
{% endif %}
{% if form.instance.excludes %}
  <b>Excludes</b>
  <ul>
    {% for item in form.instance.get_excludes %}
      <li>{{ item }}</li>
    {% endfor %}
  </ul>
{% endif %}

<hr>
<h3>Make Changes</h3>
{% include "snippets/form-snippet.html" with form=form %}
{% endblock content %}}

menus/templates/menus/item_detail.html
{% extends "base.html" %}

  {% block head_title %}Menu Itens || {{block.super}} {% endblock head_title %}

{% block content %}
<h1>{{ object.name }}</h1>
<h2>{{ object.restaurant.name }}<small> {{object.restaurant.location}}</small></h2>
{% if object.contents %}
  <b>Contents</b>
  <ul>
    {% for item in object.get_contents %}
      <li>{{ item }}</li>
    {% endfor %}
  </ul>
{% endif %}
{% if object.excludes %}
  <b>Excludes</b>
  <ul>
    {% for item in object.get_excludes %}
      <li>{{ item }}</li>
    {% endfor %}
  </ul>
{% endif %}

{% endblock content %}}

menus/templates/menus/item_list.html
{% extends "base.html" %}

  {% block head_title %}Menu Itens || {{block.super}} {% endblock head_title %}

{% block content %}
<h1>Menu Items <small><a href="{% url 'menus:create' %}">Add</a></small></h1>

<ul>
  {% for obj in object_list %}
    <li><a href="{{ obj.get_absolute_url }}">{{ obj.name }}</a><br>
      {% if obj.contents %}
        Contents
        <ul>
          {% for item in obj.get_contents %}
            <li>{{ item }}</li>
          {% endfor %}
        </ul>
      </li>
      {% endif %}
      {% if obj.excludes %}
        Excludes
        <ul>
          {% for item in obj.get_excludes %}
            <li>{{ item }}</li>
          {% endfor %}
        </ul>
      </li>
      {% endif %}
      {% empty %}
        <a href="{% url 'menus:create' %}">Add</a>
  {% endfor %}
</ul>
{% endblock content %}}